### ISSUE TITLE
Migrating once bintray sunset? 

### ISSUE THREAD

**Issue by NolanC33** [Chrismarsh/conan-gsl#1]
Happy Monday,

It appears that bintray is getting sunset: 

![image](https://user-images.githubusercontent.com/11447537/123703618-97b33280-d832-11eb-92d7-00887296b4ca.png)

Will you be uploading the build artifacts to a different location?

Thanks.

**Comment by NolanC33** [comment]
I was thinking I may and try and contribute it to Conan-Central. https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md

**Comment by Chrismarsh** [comment]
Yes, bintray being sunset has been a major pain for me. I maintain these conan-* to support the development of a numerical model. 

Currently I work around this by building everything locally:
https://github.com/Chrismarsh/CHM/blob/master/conan_export_deps.sh
but this is useless for CI testing. 

I am in the process of getting some cloud infrastructure to host Artifactory, but that's probably next-week at the earliest. 

In passing I have thought about contributing to conan-centre, but I don't have the time to take on even more of a support burden. It's unclear to me how much extra of a support burden this would entail.

**Comment by NolanC33** [comment]
Gotcha. If its alright with you, I was thinking I'd give it a shot. Basically I think I would be copy pasting this repo here, with minor adjustments.

**Comment by Chrismarsh** [comment]
Please, feel free to contribute to conan-centre based off this! I've added a MIT license to both master and the stable/2.x branch just to make it simple for you. 

If you could let me know how it goes that would be great.

**Comment by NolanC33** [comment]
Awesome, will do :+1:

**Comment by NolanC33** [comment]
Working on it here https://github.com/conan-io/conan-center-index/pull/6098

**Comment by Croydon** [comment]
@Chrismarsh Do you need specific builds that CCI is not generating? Otherwise maintaining own infrastructure and builds has probably no advantages 🤔

**Comment by Chrismarsh** [comment]
@Croydon The numerical model I develop (linked above) is standard scientific-code fare in that it requires specific (some esoteric) dependencies at specific revisions with specific build flags. A bunch are built generically, e.g., this one. A few are quite specific to my needs, e.g., my conan-gdal (https://github.com/Chrismarsh/conan-gdal/blob/stable/gdal3/conanfile.py#L114) where I don't include the vast majority of geospatial drivers as my code doesn't need it.

I agree that maintaining my own infrastructure and builds is deeply sub-optimal. When bintray existed, it was a simple solution -- customized builds -> upload to bintray. And it Just Worked (tm). Now I am in the awkward position of that not working.

I was unsure how difficult it was to contribute to CCI the more general builds, and I'd already lost so much time to this I wasn't interested in taking it on as Yet Another Thing. E.g., who is responsible for updating the build scripts to include new versions of a library?

If CCI could include the generic libraries, that would of course be ideal. Are you associated with CCI? Do you have a sense to this?

**Comment by Croydon** [comment]
I'm one of the [official community reviewers of CCI](https://github.com/conan-io/conan-center-index/blob/75e02584f5d84f74503879e5d27bf97e44b2a389/docs/review_process.md#community-reviewers) and I'm also part of [Bincrafters](https://github.com/bincrafters).

Many questions are answered in the docs: https://github.com/conan-io/conan-center-index/blob/master/docs/

> E.g., who is responsible for updating the build scripts to include new versions of a library?

Anyone / nobody / the community. Whoever is motivated to create pull requests.

I think you might also be interested in a feature like this: https://github.com/bincrafters/community/issues/1383
E.g. having the recipe completely in CCI and if you need builds which are not [generated by CCI](https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md) then build them on your own CI and upload the builds to your own Conan remote.

**Comment by NolanC33** [comment]
> Working on it here [conan-io/conan-center-index#6098](https://github.com/conan-io/conan-center-index/pull/6098)

Merged :)
